### ISSUE TITLE
self-commenting produced mongoengine Validation Error

### ISSUE THREAD

**Issue by drpiccioni** [BaySchoolCS2/ProjectRepo#108]
git pull approx 12:20 PM 5/26/15
deleted database
signed in
verified email
logged in
created a post
commented on my own post
mongongine.errors.ValidationError:

``` python
Traceback (most recent call last):
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drp/Documents/projects/ProjectRepo/application/post.py", line 123, in newComment
    post.save()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/mongoengine/document.py", line 287, in save
    self.validate(clean=clean)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/mongoengine/base/document.py", line 411, in validate
    raise ValidationError(message, errors=errors)
ValidationError: ValidationError (Posts:5564c8f7dcef2b0bd3c01c98) (body.StringField only accepts string values: ['comments'])
```

**Comment by michardy** [comment]
Fixed
