### ISSUE TITLE
clicking username for a post -> application.collections.DoesNotExist

### ISSUE THREAD

**Issue by drpiccioni** [BaySchoolCS2/ProjectRepo#115]
git pull approx 1:10 PM 5/26/15
database contains one member and one post
$./run.py
open browser
see the one post (without logging in)
click username for the post
get application.collections.DoesNotExist

``` python
Traceback (most recent call last):
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/drp/Documents/projects/ProjectRepo/application/home.py", line 26, in profile
    user = User.objects(alias = session.get("alias")).get()
  File "/home/drp/Documents/projects/ProjectRepo/venv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 239, in get
    raise queryset._document.DoesNotExist(msg)
DoesNotExist: User matching query does not exist.
```

**Comment by michardy** [comment]
Fixed
