### ISSUE TITLE
macro render post breaks home page

### ISSUE THREAD

**Issue by michardy** [BaySchoolCS2/ProjectRepo#84]
``` python
Traceback (most recent call last):
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Code/CS2/ProjectRepo/application/home.py", line 14, in index
    return render_template('index.html', posts = paginated_posts, page = page) # variables go after template
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/ProjectRepo/application/templates/index.html", line 1, in top-level template code
    {% extends 'header.html' %}
  File "/home/michael/Code/CS2/ProjectRepo/application/templates/header.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/michael/Code/CS2/ProjectRepo/application/templates/layout.html", line 19, in top-level template code
    {% block body %}
  File "/home/michael/Code/CS2/ProjectRepo/application/templates/index.html", line 7, in block "body"
    {{ macros.renderPost(post) }}
  File "/home/michael/Code/CS2/ProjectRepo/application/templates/macros.html", line 7, in template
    posted {{ moment(post.created_at).fromNow() }}
UndefinedError: 'moment' is undefined
```

**Comment by michardy** [comment]
Is this because of an update to the package  requirements.

**Comment by fhebert-perkins** [comment]
Fixed
