### ISSUE TITLE
cannot veiw posts if not logged in

### ISSUE THREAD

**Issue by michardy** [BaySchoolCS2/ProjectRepo#90]
I can view posts when I am logged it but when I am not I cannot view the posts page

``` python
Traceback (most recent call last):
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michael/Code/CS2/ProjectRepo/application/post.py", line 19, in viewPost
    user = User.objects(alias = session.get("alias")).get()
  File "/home/michael/Code/CS2/ProjectRepo/venv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 239, in get
    raise queryset._document.DoesNotExist(msg)
DoesNotExist: User matching query does not exist.
```

**Comment by michardy** [comment]
Fixed
