### ISSUE TITLE
Following does not work

### ISSUE THREAD

**Issue by michardy** [BaySchoolCS2/ProjectRepo#96]
``` python
Traceback (most recent call last):
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 265, in error_router
    return original_handler(e)
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/flask/app.py", line 1577, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/werkzeug/wrappers.py", line 841, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/michael/Code/CS2/fork/me/ProjectRepo/venv/lib/python2.7/site-packages/werkzeug/test.py", line 867, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'Subscriptions' object is not callable
```

**Comment by michardy** [comment]
Works
